# 1. Chargement des données

## Les Importations et le Chargement

In [7]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('../data/data.csv', sep=';', encoding='latin1')
df.head()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,3,3,2,right ocular pain,1,1,2,...,36.6,100,2,Corneal abrasion,1,4,2,86,"5,00",1
1,1,1,56,12,3,2,right forearm burn,1,1,2,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,"3,95",1
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2,...,36.6,98,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,"1,00",1
3,1,2,71,8,1,1,ascites tapping,1,1,3,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,"9,83",1
4,1,2,58,4,3,1,"distension, abd",1,1,3,...,36.5,NaN,4,Ascites,1,5,8,109,"6,60",1

In [19]:
with open('../data/data.csv', 'r', encoding='latin1') as f:
    for i in range(5):
        print(f.readline())

Group;Sex;Age;Patients number per hour;Arrival mode;Injury;Chief_complain;Mental;Pain;NRS_pain;SBP;DBP;HR;RR;BT;Saturation;KTAS_RN;Diagnosis in ED;Disposition;KTAS_expert;Error_group;Length of stay_min;KTAS duration_min;mistriage

2;2;71;3;3;2;right ocular pain;1;1;2;160;100;84;18;36.6;100;2;Corneal abrasion;1;4;2;86;5,00;1

1;1;56;12;3;2;right forearm burn;1;1;2;137;75;60;20;36.5;;4;Burn of hand, firts degree dorsum;1;5;4;64;3,95;1

2;1;68;8;2;2;arm pain, Lt;1;1;2;130;80;102;20;36.6;98;4;Fracture of surgical neck of humerus, closed;2;5;4;862;1,00;1

1;2;71;8;1;1;ascites tapping;1;1;3;139;94;88;20;36.5;;4;Alcoholic liver cirrhosis with ascites;1;5;6;108;9,83;1

# Identifier les colonnes avec des caractères spéciaux (comme #BOÞ!,?, #BOŞ!, '']

#Convertir les signes vitaux (SBP, DBP, HR, etc.) en format numérique.
#Ligne avec trop de données manquantes, supprimer vs remplissage#Convertir les signes vitaux (SBP, DBP, HR, etc.) en format numérique.
#Ligne avec trop de données manquantes, supprimer vs remplissage

In [20]:
def clean_value(valeur):
    v = valeur.strip()
    valeurs_invalides = ['??', '#BOŞ!', '#BOÞ!', '']
    if v in valeurs_invalides:
        return "N/A"
    v_modifiee = v.replace(',', '.')
    try:
        float(v_modifiee)
        return v_modifiee
    except ValueError:
        return v

In [21]:
donnees_nettoyees = []

with open('../data/data.csv', 'r', encoding='latin-1') as fin:
    next(fin)
    for ligne in fin:
        token = ligne.strip().split(';')

        try:
            if len(token) >= 20:
                ligne_propre = [
                    clean_value(token[1]),  # Sex
                    clean_value(token[2]),  # Age
                    clean_value(token[4]),  # Arrival mode
                    clean_value(token[5]),  # Injury
                    clean_value(token[7]),  # Mental
                    clean_value(token[8]),  # Pain
                    clean_value(token[9]),  # NRS_pain
                    clean_value(token[10]), # SBP
                    clean_value(token[11]), # DBP
                    clean_value(token[12]), # HR
                    clean_value(token[13]), # RR
                    clean_value(token[14]), # BT
                    clean_value(token[15]), # Saturation
                    clean_value(token[19])  # KTAS_expert
                ]
                donnees_nettoyees.append(ligne_propre)

        except IndexError:
            continue

print(f"Tableau créé avec {len(donnees_nettoyees)} lignes.")

Tableau créé avec 1267 lignes.

In [22]:
# Définir les noms des colonnes que tu as extraites
colonnes = [
    'Sex', 'Age', 'Arrival_mode', 'Injury', 'Mental', 'Pain', 
    'NRS_pain', 'SBP', 'DBP', 'HR', 'RR', 'BT', 'Saturation', 'KTAS_expert'
]

In [23]:
# Créer le nouveau DataFrame
df_final = pd.DataFrame(donnees_nettoyees, columns=colonnes)

In [24]:
# Remplacer tes "N/A" par de vrais NaN pour que Pandas les reconnaisse
df_final = df_final.replace('N/A', np.nan)

# Afficher un aperçu
df_final.head()

,Sex,Age,Arrival_mode,Injury,Mental,Pain,NRS_pain,SBP,DBP,HR,RR,BT,Saturation,KTAS_expert
0,2,71,3,2,1,1,2,160,100,84,18,36.6,100,4
1,1,56,3,2,1,1,2,137,75,60,20,36.5,NaN,5
2,1,68,2,2,1,1,2,130,80,102,20,36.6,98,5
3,2,71,1,1,1,1,3,139,94,88,20,36.5,NaN,5
4,2,58,3,1,1,1,3,91,67,93,18,36.5,NaN,5

In [ ]:
# Convertir les colonnes en numérique (force les erreurs en NaN)
cols_numeriques = ['Age', 'SBP', 'DBP', 'HR', 'RR', 'BT', 'Saturation']

for col in cols_numeriques:
    df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

# Vérifier les types
print(df_final.dtypes)